#example deployment and post customsiation for Windows VM
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: withwifi
spec:
  hardware:
    cpus: 2
    memory: 8Gi

---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: windows-file-server
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: withwifi
  imageName: 10.221.124.112/Windows-testVm.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
