apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: best-effort-ec-small
  # No resource requests/reservations.
  # Memory overcommit possible.
spec:
  # VM operator controller name for VirtualMachine class
  # is different so addition of controllerName attr with invalid
  # value makes vm operator ignore this VM CRD instance.
  # This is majorly done because vm operator doesn't have all the
  # needed capabilities to deploy ec worker vm.
  controllerName: vmoperator.vmware.com/ecworker
  hardware:
    cpus: 4
    memory: 8Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: ec-system
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ec-worker
  namespace: ec-system
spec:
  className: best-effort-ec-small
  imageName: ec-wrkr.ova
  powerState: poweredOff
  vmMetadata:
    configMapName: user-data-ubuntu
    transport: CloudInit

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-data-ubuntu
  namespace: ec-system
data:
  networkconfig: |
        version: 2
        ethernets:
            eth0:
                dhcp: "false"
                addresses:
                    - 172.16.0.159/16
                nameservers:
                    addresses:
                        - 10.221.124.97
                routes:
                    - to: 0.0.0.0/0
                      via: 172.16.255.254
