apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: abb-ssc600
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: my-vm-class-1
  imageName: 10.221.124.112/ssc600_disk.ova
  powerState: poweredOff
  networkInterfaces:
    - networkName: "VM Network"
      ethernetCardType: "vmxnet3"


---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: my-vm-class-1
spec:
  hardware:
    cpus: 4
    memory: 8Gi
  policies:
    resources:
      requests:
        cpu: 4
        memory: 8Gi
  configSpec:
    sched.cpu.latencySensitivity: high
    sched.mem.lpage.enable1GPage: true
    sched.cpu.affinity.exclusiveNoStats: true
    monitor.forceEnableMPTI: true
    timeTracker.lowLatency: true

