apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: ecsmonitoring-metrics
  namespace: esx-system
spec:
  metrics-collection:
    enabled: true
    metrics-sink:
      url: "http://172.16.204.69:30777/api/v1/write"
      data-format: "prometheusremotewrite"
