apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: docker.io/busybox
    command
      - sleep
      - "36000000"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
